Challenge 1 core concepts and styling
Alfonsini/react-certification-2020 pull request #1
Opened 2021-03-22 10:45 UTC by Alfonsini

Mini-Challenge 1: Core Concepts + Styling => complete

2021-03-24 08:01 UTC, erickwize requested changes
## Comments (Mini-challenge 1 & 2)
Good work with the UI and the CSS the app looks very good! Also, nice work adding the hover animation to the sidebar and the elements in the sidebar!
I see you still don't have tests, we encourage you to start doing some tests for your components. You can use [React testing library](https://testing-library.com/docs/react-testing-library/intro/).
I recommend watching the styling part of the course, the styled-components were not implemented in the deliverable.

## Acceptance Criteria (Mini-challenge 1)
- [x] The header is rendered correctly.
- [x] A list of videos obtained from a mock file is displayed in the **Home View**.
- [x] CSS styles are applied correctly using the styled-components approach.

## Bonus Points (Mini-challenge 1)
- [x] No warnings or errors are logged in the browser console.
- [x] The UI is responsive

## Acceptance Criteria (Mini-challenge 2)
- [ ] Meaningful test cases were implemented for components and sub-routines logic.
- [ ] All the test cases were successful.

## Bonus Points (Mini-challenge 2)
- [ ] Test coverage is above 60%.

2021-03-24 08:01 UTC, erickwize commented on src/components/Video/Video.component.jsx
> +                      className="style-scope yt-icon"
We encourage you to use Styled components instead of using CSS modules

2021-03-24 08:01 UTC, erickwize commented on src/components/Video/Video.styles.css
> +a {
Instead of having a big CSS file, we encourage you to have CSS in JS with styled-components and you could also use [Less syntax](http://lesscss.org/#nesting) to write less css.

2021-03-24 08:01 UTC, erickwize commented on src/components/core/AppContent/AppContent.component.jsx
> +  return <div className="app-content scroll ">{children}</div>;
Same CSS module comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/AppContent/AppContent.styles.css
> +.app-content {
Same CSS comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/BlankPage/BlankPage.component.jsx
> +  return <div className="blank" />;
Same CSS module comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Menus/Horizontal.component.jsx
> +          <span className="text-truncate ">Favorites</span>
Same CSS module comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Menus/Vertical.component.jsx
> +          <span className="text-truncate ">Favorities</span>
Same CSS module comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Navbar/Navbar.component.jsx
> +      </nav>
Same CSS module comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Navbar/Navbar.component.jsx
> +      </nav>
If you used [styled-components you could use the props](https://styled-components.com/docs/basics#adapting-based-on-props) in the component to render things differently.

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Navbar/Navbar.styles.css
> +.navbar-container {
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Search/Search.component.jsx
> +    </div>
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Search/Search.styles.css
> +.search {
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Sidebar/Sidebar.component.jsx
> +      <div className="shadow-bottom" />
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/components/core/Sidebar/Sidebar.styles.css
> +.navbar-aside-container {
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/pages/Home/Home.page.jsx
> +          <div className="col" key={v.id.videoId.toString()}>
Same CSS modules comment here

2021-03-24 08:01 UTC, erickwize commented on src/pages/Home/Home.styles.css
> +.col {
Same CSS modules comment here

2021-04-04 07:43 UTC, Alfonsini commented on src/components/Video/Video.component.jsx
> +                      className="style-scope yt-icon"
Hi Erick, I changed to use styled components 😃 thanks for your comment.

2021-04-04 07:45 UTC, Alfonsini commented on src/components/core/AppContent/AppContent.styles.css
> +.app-content {
Hi Erick, I changed to use styled components 😃 thanks for your comment.

2021-04-04 07:45 UTC, Alfonsini commented on src/components/core/AppContent/AppContent.component.jsx
> +  return <div className="app-content scroll ">{children}</div>;
Hi Erick, I changed to use styled components 😃 thanks for your comment.

2021-04-04 07:45 UTC, Alfonsini commented on src/components/Video/Video.styles.css
> +a {
Hi Erick, I changed to use styled components 😃 thanks for your comment.

2021-04-04 07:45 UTC, Alfonsini commented on src/pages/Home/Home.styles.css
> +.col {
Hi Erick, I changed to use styled components 😃 thanks for your comment.

2022-03-05 04:00 UTC, merged